export const picks = {
  "Senate confirmation required": [
    { 
      name: 'Pamela Bondi', 
      image: 'pamela-bondi',
      department: 'AG', 
      title: "Attorney General", 
      status: "Announced",
    },  
    { 
      name: 'Marco Rubio', 
      image: 'marco-rubio',
      department: 'State', 
      title: "Secretary of State", 
      status: "Announced",
    }, 
    { 
      name: 'Pete Hegseth', 
      image: 'pete-hegseth',
      department: 'Defense', 
      title: "Secretary of Defense", 
      status: "Announced",
    },  
    { 
      name: 'Kristi Noem', 
      image: 'kristi-noem',
      department: 'Homeland', 
      title: "Secretary of Homeland Security", 
      status: "Announced",
    },  
    { 
      name: 'Lori Chavez-DeRemer', 
      image: 'lori-chavez-deremer',
      department: 'Labor', 
      title: "Secretary of Labor", 
      status: "Announced",
    },      
    { 
      name: 'Robert F. Kennedy, Jr.', 
      image: 'robert-kennedy-jr',
      department: 'HHS', 
      title: "Secretary of Health & Human Services", 
      status: "Announced",
    },      { 
      name: 'Doug Burgum', 
      image: 'doug-burgum',
      department: 'Interior', 
      title: "Secretary of the Interior", 
      status: "Announced",
    },  
    { 
      name: 'Doug Collins', 
      image: 'doug-collins',
      department: 'VA', 
      title: "Secretary of Veteran Affairs", 
      status: "Announced",
    },      
    { 
      name: 'Scott Bessent', 
      image: 'scott-bessent',
      department: 'Treasury', 
      title: "Secretary of the Treasury", 
      status: "Announced",
    },  
    { 
      name: 'Brooke Rollins', 
      image: 'brooke-rollins',
      department: 'Agriculture', 
      title: "Secretary of Agriculture", 
      status: "Announced",
    },     
    { 
      name: 'Howard Lutnick', 
      image: 'howard-lutnick',
      department: 'Commerce', 
      title: "Secretary of Commerce", 
      status: "Announced",
    },  
    { 
      name: 'Sean Duffy', 
      image: 'sean-duffy',
      department: 'Transport.', 
      title: "Secretary of Transportation", 
      status: "Announced",
    },      
    { 
      name: 'Chris Wright', 
      image: 'chris-wright',
      department: 'Energy', 
      title: "Secretary of Energy", 
      status: "Announced",
    }, 
    { 
      name: 'Linda McMahon', 
      image: 'linda-mcmahon',
      department: 'Education', 
      title: "Secretary of Education", 
      status: "Announced",
    },  
    { 
      name: 'Scott Turner', 
      image: 'scott-turner',
      department: 'Housing', 
      title: "Secretary of Housing & Urban Development", 
      status: "Announced",
    }, 
    { 
      name: 'John Ratcliffe', 
      image: 'john-ratcliffe',
      department: 'CIA', 
      title: "Director of the Central Intelligence Agency", 
      status: "Announced",
    },  
    { 
      name: 'Tulsi Gabbard', 
      image: 'tulsi-gabbard',
      department: 'DNI', 
      title: "Director of National Intelligence", 
      status: "Announced",
    },      
    { 
      name: 'Mehmet Oz', 
      image: 'mehmet-oz',
      department: 'MMS', 
      title: "Administrator of the Centers for Medicare and Medicaid Services", 
      status: "Announced",
    },  
    { 
      name: 'Lee Zeldin', 
      image: 'lee-zeldin',
      department: 'EPA', 
      title: "Administrator of the Environmental Protection Agency", 
      status: "Announced",
    },      
    { 
      name: 'Elise Stefanik', 
      image: 'elise-stefanik',
      department: 'UN', 
      title: "U.S. Ambassador to the United Nations", 
      status: "Announced",
    },  
    { 
      name: 'Martin Makary', 
      image: 'martin-makary',
      department: 'FDA', 
      title: "Director of the Food & Drug Administration", 
      status: "Announced",
    },      
    { 
      name: 'Matthew Whitaker', 
      image: 'matthew-whitaker',
      department: 'NATO', 
      title: "United States Ambassador to the North Atlantic Treaty Organization", 
      status: "Announced",
    },  
    { 
      name: 'Dave Weldon', 
      image: 'dave-weldon',
      department: 'CDC', 
      title: "Director of the Centers for Disease Control and Prevention", 
      status: "Announced",
    },      { 
      name: 'Janette Nesheiwat', 
      image: 'janette-nesheiwat',
      department: 'Surgeon General', 
      title: "Surgeon General of the United States", 
      status: "Announced",
    },  
    { 
      name: 'Russell Vought', 
      image: 'russell-vought',
      department: 'OMB', 
      title: "Director of the Office of Management and Budget", 
      status: "Announced",
    },      
    { 
      name: 'Not yet announced', 
      image: 'placeholder',
      department: 'SBA', 
      title: "Administrator of the Small Business Administration", 
      status: "Vacant",
    }, 
    { 
      name: 'Not yet announced', 
      image: 'placeholder',
      department: 'Trade Rep.', 
      title: "United States Trade Representative", 
      status: "Vacant",
    }, 
    { 
      name: 'Not yet announced', 
      image: 'placeholder',
      department: 'CEA', 
      title: "Chair of the Council of Economic Advisers", 
      status: "Vacant",
    }, 
  ],

  "No confirmation required": [
    { 
      name: 'JD Vance', 
      image: 'jd-vance',
      department: 'VP', 
      title: "Vice President", 
      status: "Elected",
    }, 
    { 
      name: 'Susie Wiles', 
      image: 'susie-wiles',
      department: 'Chief of Staff', 
      title: "Chief of Staff", 
      status: "Named",
    }, 
    { 
      name: 'James Blair', 
      image: 'james-blair',
      department: 'DCS', 
      title: "Deputy Chief of Staff", 
      status: "Named",
    }, 
    { 
      name: 'Taylor Budowich', 
      image: 'taylor-budowich',
      department: 'DCS', 
      title: "Deputy Chief of Staff", 
      status: "Named",
    }, 
    { 
      name: 'Stephen Miller', 
      image: 'stephen-miller',
      department: 'DCS', 
      title: "Deputy Chief of Staff", 
      status: "Named",
    }, 
    { 
      name: 'Dan Scavino', 
      image: 'dan-scavino',
      department: 'DCS', 
      title: "Deputy Chief of Staff", 
      status: "Named",
    }, 
    { 
      name: 'Thomas Homan', 
      image: 'thomas-homan',
      department: 'Border Czar', 
      title: "United States Presidential Advisor on Border Security", 
      status: "Named",
    }, 
    { 
      name: 'Michael Waltz', 
      image: 'michael-waltz',
      department: 'NSA', 
      title: "United States National Security Advisor", 
      status: "Named",
    }, 
    { 
      name: 'Bill McGinley', 
      image: 'bill-mcginley',
      department: 'WH Counsel', 
      title: "White House Counsel", 
      status: "Named",
    }, 
    { 
      name: 'Steven Cheung', 
      image: 'steven-cheung',
      department: 'Comm. Director', 
      title: "White House Communications Director", 
      status: "Named",
    }, 
    { 
      name: 'Karoline Leavitt', 
      image: 'karoline-leavitt',
      department: 'Press Secretary', 
      title: "Press Secretary", 
      status: "Named",
    }, 
    { 
      name: 'Will Scharf', 
      image: 'will-scharf',
      department: 'Press Secretary', 
      title: "Press Secretary", 
      status: "Named",
    }, 
    { 
      name: 'Sergio Gor', 
      image: 'sergio-gor',
      department: 'Personnel', 
      title: "Director of the White House Presidential Personnel Office", 
      status: "Named",
    }, 
    { 
      name: 'Elon Musk', 
      image: 'elon-musk',
      department: 'Efficiency', 
      title: "Co-Commissioner of the Department of Government Efficiency", 
      status: "Named",
    }, 
    { 
      name: 'Vivek Ramaswamy', 
      image: 'vivek-ramaswamy',
      department: 'Efficiency', 
      title: "Co-Commissioner of the Department of Government Efficiency", 
      status: "Named",
    }, 
    { 
      name: 'Brendan Carr', 
      image: 'brendan-carr',
      department: 'FCC', 
      title: "Chairman of the Federal Communications Commission", 
      status: "Named",
    }, 
    { 
      name: 'Alex Wong', 
      image: 'placeholder',
      department: 'Dep. NSA', 
      title: "United States Principal Deputy National Security Advisor", 
      status: "Named",
    }, 
    { 
      name: 'Sebastian Gorka', 
      image: 'sebastian-gorka',
      department: 'Dep. Asst. to the President', 
      title: "Deputy Assistant to the President / Senior Director for Counterterrorism", 
      status: "Named",
    }, 
  ],

  "Withdrawn": [
    { 
      name: 'Matt Gaetz', 
      image: 'matt-gaetz',
      department: 'AG', 
      title: "Attorney General", 
      status: "Withdrawn",
    }, 
  ]
};